"""add tag_merges table

Revision ID: 107030b9db03
Revises: f97df5517de5
Create Date: 2026-05-14 12:05:15.748696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107030b9db03'
down_revision: Union[str, Sequence[str], None] = 'f97df5517de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_merges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_name', sa.String(length=100), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['to_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_merges_id'), 'tag_merges', ['id'], unique=False)
    op.drop_index(op.f('articles_embedding_idx'), table_name='articles', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('articles_embedding_idx'), 'articles', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_tag_merges_id'), table_name='tag_merges')
    op.drop_table('tag_merges')
    # ### end Alembic commands ###
