"""add_is_starred_to_articles

Revision ID: 9e285665e775
Revises: 107030b9db03
Create Date: 2026-06-24 13:12:51.449673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e285665e775'
down_revision: Union[str, Sequence[str], None] = '107030b9db03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_starred', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_starred')
    # ### end Alembic commands ###
